service: credit-card-bonuses-api

useDotenv: true

custom:
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs18.x
  memorySize: 128
  timeout: 5
  logRetentionInDays: 30
  httpApi:
    cors: true

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

plugins:
  - serverless-esbuild
  - serverless-offline
