name: (CI) Tests
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm i
      - run: pnpm generate
      - run: pnpm lint:format
      - run: pnpm lint:linter
      - run: pnpm lint:typecheck
      - run: pnpm lint:openapi
      - run: pnpm test
