name: Test
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm i

      # Codegen
      - run: pnpm generate

      # Tests
      - run: pnpm lint:biome
      - run: pnpm lint:typescript
      - run: pnpm test
